-- ФКУ Компас: базовая схема для TMA и админ-панели.
-- Выполнять в Supabase SQL Editor. Политики RLS нужно адаптировать под выбранную авторизацию админов.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null unique,
  first_name text,
  daily_phe integer not null default 300,
  aks_portions integer not null default 4,
  is_blocked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  cat text not null,
  kcal numeric,
  protein numeric,
  fat numeric,
  carbs numeric,
  phe numeric not null default 0,
  gi numeric,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wiki_articles (
  id bigint generated by default as identity primary key,
  title text not null,
  icon text,
  body text not null,
  sort_order integer not null default 100,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.diary_entries (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  entry_date date not null,
  meal_type text not null,
  food_name text not null,
  weight_g numeric not null default 0,
  phe_mg numeric not null default 0,
  protein_g numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.aks_logs (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  log_date date not null,
  portion_index integer not null,
  is_taken boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint aks_logs_unique_portion unique (telegram_id, log_date, portion_index)
);

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null,
  author_name text,
  title text not null,
  ingredients jsonb not null default '[]'::jsonb,
  cooked_weight numeric not null default 0,
  phe_per_100 numeric not null default 0,
  prot_per_100 numeric not null default 0,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  telegram_id bigint primary key,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  admin_telegram_id bigint,
  action text not null,
  table_name text not null,
  row_id text,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists diary_entries_user_date_idx on public.diary_entries (telegram_id, entry_date);
create index if not exists aks_logs_user_date_idx on public.aks_logs (telegram_id, log_date);
create index if not exists products_active_cat_idx on public.products (is_active, cat, sort_order);
create index if not exists wiki_published_order_idx on public.wiki_articles (is_published, sort_order);
create index if not exists recipes_public_user_idx on public.recipes (is_public, telegram_id);

-- Для разработки можно временно оставить таблицы без RLS.
-- Для продакшена включите RLS и настройте политики/Edge Function проверки Telegram initData.
